In [2]:
#1.	In df, use apply method to replace the missing values in Min.Price with the column’s mean and those in Max.Price with the column’s median.
import numpy as np
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
d={'Min.Price':np.nanmean,'Max.Price':np.nanmedian}
df[['Min.Price','Max.Price']]=df[['Min.Price','Max.Price']].apply(lambda x,d:x.fillna(d[x.name](x)),args=(d,))
print(df)

   Manufacturer          Model     Type  Min.Price  Price  Max.Price  \
0         Acura        Integra    Small  12.900000   15.9      18.80
1           NaN         Legend  Midsize  29.200000   33.9      38.70
2          Audi             90  Compact  25.900000   29.1      32.30
3          Audi            100  Midsize  17.118605   37.7      44.60
4           BMW           535i  Midsize  17.118605   30.0      19.15
5         Buick        Century  Midsize  14.200000   15.7      17.30
6         Buick        LeSabre    Large  19.900000   20.8      19.15
7         Buick     Roadmaster    Large  22.600000   23.7      24.90
8         Buick        Riviera  Midsize  26.300000   26.3      26.30
9      Cadillac        DeVille    Large  33.000000   34.7      36.30
10     Cadillac        Seville  Midsize  37.500000   40.1      42.70
11    Chevrolet       Cavalier  Compact   8.500000   13.4      18.30
12    Chevrolet        Corsica  Compact  11.400000   11.4      11.40
13    Chevrolet         Camaro   Sporty  13.400000   15.1      16.80
14    Chevrolet         Lumina  Midsize  13.400000   15.9      18.40
15    Chevrolet     Lumina_APV      Van  14.700000   16.3      18.00
16    Chevrolet          Astro      Van  14.700000   16.6      18.60
17    Chevrolet        Caprice    Large  18.000000   18.8      19.60
18    Chevrolet       Corvette   Sporty  34.600000   38.0      41.50
19          NaN       Concorde    Large  18.400000   18.4      18.40
20     Chrysler        LeBaron  Compact  14.500000   15.8      17.10
21     Chrysler       Imperial    Large  29.500000   29.5      29.50
22        Dodge           Colt    Small   7.900000    9.2      10.60
23        Dodge         Shadow    Small   8.400000   11.3      14.20
24        Dodge         Spirit  Compact  11.900000   13.3      14.70
25        Dodge        Caravan      Van  17.118605   19.0      24.40
26        Dodge        Dynasty  Midsize  14.800000   15.6      16.40
27        Dodge        Stealth   Sporty  18.500000   25.8      33.10
28        Eagle         Summit    Small   7.900000   12.2      16.50
29        Eagle         Vision    Large  17.118605   19.3      21.20
..          ...            ...      ...        ...    ...        ...
63       Nissan         Sentra    Small   8.700000   11.8      14.90
64       Nissan         Altima  Compact  13.000000   15.7      18.30
65       Nissan          Quest      Van  16.700000   19.1      21.50
66       Nissan         Maxima  Midsize  21.000000   21.5      22.00
67   Oldsmobile        Achieva  Compact  13.000000   13.5      14.00
68   Oldsmobile  Cutlass_Ciera  Midsize  14.200000   16.3      18.40
69   Oldsmobile     Silhouette      Van  19.500000   19.5      19.50
70   Oldsmobile   Eighty-Eight    Large  19.500000   20.7      21.90
71     Plymouth          Laser   Sporty  11.400000   14.4      17.40
72      Pontiac         LeMans    Small  17.118605    9.0       9.90
73      Pontiac        Sunbird  Compact   9.400000   11.1      12.80
74      Pontiac       Firebird      NaN  14.000000   17.7      21.40
75      Pontiac     Grand_Prix  Midsize  15.400000   18.5      21.60
76      Pontiac     Bonneville    Large  19.400000   24.4      29.40
77         Saab            900  Compact  20.300000   28.7      37.10
78       Saturn             SL    Small   9.200000    NaN      12.90
79       Subaru          Justy    Small   7.300000    8.4       9.50
80       Subaru         Loyale    Small  10.500000   10.9      11.30
81       Subaru         Legacy  Compact  16.300000   19.5      22.70
82       Suzuki          Swift      NaN   7.300000    8.6      19.15
83       Toyota         Tercel    Small  17.118605    9.8      11.80
84       Toyota         Celica   Sporty  14.200000   18.4      22.60
85       Toyota          Camry  Midsize  15.200000    NaN      21.20
86       Toyota         Previa      Van  17.118605   22.7      26.60
87   Volkswagen            Fox    Small   8.700000    9.1       9.50
88   Volkswagen        Eurovan      Van  16.600000   19.7      22.70
89   Volkswagen         Passat  Compact  17.600000   20.0      22.40
90   Volkswagen        Corrado   Sporty  22.900000   23.3      23.70
91        Volvo            240  Compact  21.800000   22.7      23.50
92          NaN            850  Midsize  24.800000   26.7      28.50

    MPG.city  MPG.highway             AirBags DriveTrain  \
0       25.0         31.0                None      Front
1       18.0         25.0  Driver & Passenger      Front
2       20.0         26.0         Driver only      Front
3       19.0         26.0  Driver & Passenger        NaN
4       22.0         30.0                 NaN       Rear
5       22.0         31.0         Driver only        NaN
6       19.0         28.0         Driver only      Front
7       16.0         25.0         Driver only       Rear
8       19.0         27.0         Driver only      Front
9       16.0         25.0         Driver only      Front
10      16.0         25.0  Driver & Passenger      Front
11      25.0         36.0                 NaN        NaN
12      25.0         34.0         Driver only      Front
13      19.0         28.0  Driver & Passenger       Rear
14       NaN         29.0                None      Front
15      18.0         23.0                None      Front
16      15.0         20.0                None        4WD
17      17.0         26.0         Driver only       Rear
18      17.0         25.0         Driver only       Rear
19      20.0         28.0  Driver & Passenger      Front
20      23.0         28.0  Driver & Passenger      Front
21      20.0         26.0         Driver only      Front
22      29.0         33.0                None      Front
23      23.0         29.0         Driver only      Front
24      22.0         27.0         Driver only      Front
25      17.0         21.0         Driver only        4WD
26      21.0          NaN         Driver only      Front
27       NaN         24.0         Driver only        4WD
28      29.0         33.0                None      Front
29      20.0         28.0  Driver & Passenger      Front
..       ...          ...                 ...        ...
63      29.0         33.0         Driver only      Front
64      24.0         30.0         Driver only      Front
65      17.0         23.0                None      Front
66      21.0         26.0         Driver only      Front
67      24.0         31.0                None      Front
68      23.0         31.0         Driver only      Front
69      18.0         23.0                None      Front
70       NaN         28.0         Driver only      Front
71       NaN         30.0                None        4WD
72      31.0         41.0                None      Front
73       NaN         31.0                None        NaN
74      19.0         28.0  Driver & Passenger       Rear
75      19.0         27.0                None      Front
76      19.0         28.0  Driver & Passenger      Front
77      20.0         26.0                 NaN      Front
78       NaN         38.0         Driver only      Front
79      33.0         37.0                None        4WD
80      25.0         30.0                None        4WD
81      23.0         30.0         Driver only        4WD
82      39.0         43.0                None      Front
83      32.0         37.0         Driver only      Front
84      25.0         32.0                 NaN      Front
85      22.0         29.0         Driver only        NaN
86      18.0         22.0         Driver only        4WD
87      25.0         33.0                None      Front
88      17.0         21.0                None      Front
89      21.0         30.0                None      Front
90      18.0         25.0                None      Front
91      21.0         28.0         Driver only       Rear
92      20.0         28.0  Driver & Passenger      Front

              ...            Passengers  Length  Wheelbase  Width  \
0             ...                   5.0   177.0      102.0   68.0
1             ...                   5.0   195.0      115.0   71.0
2             ...                   5.0   180.0      102.0   67.0
3             ...                   6.0   193.0      106.0    NaN
4             ...                   4.0   186.0      109.0   69.0
5             ...                   6.0   189.0      105.0   69.0
6             ...                   6.0   200.0      111.0   74.0
7             ...                   6.0   216.0      116.0   78.0
8             ...                   5.0   198.0      108.0    NaN
9             ...                   6.0   206.0      114.0   73.0
10            ...                   5.0   204.0      111.0   74.0
11            ...                   5.0   182.0      101.0   66.0
12            ...                   5.0   184.0      103.0   68.0
13            ...                   4.0   193.0      101.0   74.0
14            ...                   6.0     NaN      108.0   71.0
15            ...                   7.0   178.0      110.0   74.0
16            ...                   8.0   194.0      111.0   78.0
17            ...                   6.0   214.0      116.0   77.0
18            ...                   2.0   179.0       96.0   74.0
19            ...                   6.0   203.0      113.0   74.0
20            ...                   6.0   183.0      104.0   68.0
21            ...                   6.0   203.0      110.0   69.0
22            ...                   5.0   174.0       98.0   66.0
23            ...                   5.0   172.0       97.0   67.0
24            ...                   6.0   181.0      104.0   68.0
25            ...                   7.0   175.0      112.0   72.0
26            ...                   6.0   192.0      105.0   69.0
27            ...                   4.0   180.0       97.0    NaN
28            ...                   5.0   174.0       98.0   66.0
29            ...                   6.0   202.0      113.0   74.0
..            ...                   ...     ...        ...    ...
63            ...                   5.0   170.0       96.0   66.0
64            ...                   5.0   181.0      103.0   67.0
65            ...                   7.0   190.0      112.0   74.0
66            ...                   5.0   188.0      104.0   69.0
67            ...                   5.0   188.0      103.0   67.0
68            ...                   5.0   190.0      105.0   70.0
69            ...                   7.0     NaN      110.0   74.0
70            ...                   6.0   201.0      111.0   74.0
71            ...                   4.0   173.0       97.0   67.0
72            ...                   4.0   177.0       99.0   66.0
73            ...                   5.0   181.0      101.0   66.0
74            ...                   4.0   196.0      101.0   75.0
75            ...                   5.0   195.0      108.0   72.0
76            ...                   6.0   177.0      111.0   74.0
77            ...                   5.0     NaN       99.0   67.0
78            ...                   5.0   176.0      102.0   68.0
79            ...                   4.0   146.0       90.0   60.0
80            ...                   5.0   175.0       97.0   65.0
81            ...                   5.0   179.0      102.0   67.0
82            ...                   4.0   161.0       93.0    NaN
83            ...                   NaN   162.0       94.0    NaN
84            ...                   4.0   174.0       99.0   69.0
85            ...                   5.0   188.0      103.0   70.0
86            ...                   7.0   187.0      113.0   71.0
87            ...                   4.0   163.0       93.0   63.0
88            ...                   7.0   187.0      115.0   72.0
89            ...                   5.0   180.0      103.0   67.0
90            ...                   4.0   159.0       97.0   66.0
91            ...                   5.0   190.0      104.0   67.0
92            ...                   5.0   184.0      105.0   69.0

    Turn.circle Rear.seat.room  Luggage.room  Weight   Origin  \
0          37.0           26.5           NaN  2705.0  non-USA
1          38.0           30.0          15.0  3560.0  non-USA
2          37.0           28.0          14.0  3375.0  non-USA
3          37.0           31.0          17.0  3405.0  non-USA
4          39.0           27.0          13.0  3640.0  non-USA
5          41.0           28.0          16.0     NaN      USA
6          42.0           30.5          17.0  3470.0      USA
7          45.0           30.5          21.0  4105.0      USA
8          41.0           26.5          14.0  3495.0      USA
9          43.0           35.0          18.0  3620.0      USA
10         44.0           31.0           NaN  3935.0      USA
11         38.0           25.0          13.0  2490.0      USA
12         39.0           26.0           NaN  2785.0      USA
13         43.0           25.0          13.0  3240.0      USA
14          NaN           28.5          16.0  3195.0      USA
15         44.0           30.5           NaN  3715.0      USA
16         42.0           33.5           NaN  4025.0      USA
17         42.0           29.5          20.0  3910.0      USA
18         43.0            NaN           NaN  3380.0      NaN
19          NaN           31.0          15.0  3515.0      USA
20         41.0           30.5          14.0  3085.0      USA
21         44.0           36.0          17.0  3570.0      USA
22         32.0            NaN          11.0  2270.0      USA
23         38.0           26.5           NaN  2670.0      USA
24         39.0           30.5           NaN  2970.0      USA
25         42.0           26.5           NaN  3705.0      USA
26         42.0           30.5          16.0  3080.0      USA
27         40.0           20.0          11.0  3805.0      USA
28         36.0           26.5          11.0  2295.0      USA
29         40.0           30.0          15.0  3490.0      USA
..          ...            ...           ...     ...      ...
63         33.0           26.0           NaN     NaN  non-USA
64         40.0           28.5          14.0  3050.0  non-USA
65         41.0           27.0           NaN  4100.0  non-USA
66         41.0           28.5          14.0  3200.0  non-USA
67         39.0           28.0          14.0  2910.0      USA
68         42.0           28.0          16.0  2890.0      USA
69         44.0           30.5           NaN  3715.0      USA
70         42.0           31.5          17.0  3470.0      USA
71         39.0           24.5           8.0  2640.0      NaN
72         35.0           25.5          17.0  2350.0      USA
73         39.0           25.0          13.0     NaN      USA
74         43.0           25.0          13.0  3240.0      USA
75         41.0           28.5          16.0  3450.0      USA
76         43.0           30.5          18.0  3495.0      USA
77         37.0           26.5          14.0  2775.0  non-USA
78         40.0           26.5           NaN  2495.0      USA
79         32.0           23.5          10.0  2045.0  non-USA
80         35.0           27.5          15.0  2490.0  non-USA
81         37.0           27.0          14.0  3085.0  non-USA
82         34.0           27.5          10.0  1965.0  non-USA
83         36.0           24.0          11.0  2055.0  non-USA
84          NaN           23.0          13.0  2950.0  non-USA
85         38.0           28.5          15.0  3030.0  non-USA
86         41.0           35.0           NaN  3785.0  non-USA
87         34.0           26.0          10.0  2240.0  non-USA
88         38.0           34.0           NaN  3960.0      NaN
89         35.0           31.5          14.0  2985.0  non-USA
90         36.0           26.0          15.0  2810.0  non-USA
91         37.0           29.5          14.0  2985.0  non-USA
92         38.0           30.0          15.0  3245.0  non-USA

                        Make
0              Acura Integra
1               Acura Legend
2                    Audi 90
3                   Audi 100
4                   BMW 535i
5              Buick Century
6              Buick LeSabre
7           Buick Roadmaster
8              Buick Riviera
9           Cadillac DeVille
10          Cadillac Seville
11        Chevrolet Cavalier
12         Chevrolet Corsica
13          Chevrolet Camaro
14          Chevrolet Lumina
15      Chevrolet Lumina_APV
16           Chevrolet Astro
17         Chevrolet Caprice
18        Chevrolet Corvette
19         Chrylser Concorde
20          Chrysler LeBaron
21         Chrysler Imperial
22                Dodge Colt
23              Dodge Shadow
24              Dodge Spirit
25             Dodge Caravan
26             Dodge Dynasty
27             Dodge Stealth
28              Eagle Summit
29              Eagle Vision
..                       ...
63             Nissan Sentra
64             Nissan Altima
65              Nissan Quest
66             Nissan Maxima
67        Oldsmobile Achieva
68  Oldsmobile Cutlass_Ciera
69     Oldsmobile Silhouette
70   Oldsmobile Eighty-Eight
71            Plymouth Laser
72            Pontiac LeMans
73                       NaN
74          Pontiac Firebird
75        Pontiac Grand_Prix
76        Pontiac Bonneville
77                  Saab 900
78                 Saturn SL
79              Subaru Justy
80             Subaru Loyale
81             Subaru Legacy
82              Suzuki Swift
83             Toyota Tercel
84             Toyota Celica
85              Toyota Camry
86             Toyota Previa
87            Volkswagen Fox
88        Volkswagen Eurovan
89         Volkswagen Passat
90        Volkswagen Corrado
91                 Volvo 240
92                 Volvo 850

[93 rows x 27 columns]

In [8]:
#2.	Get the first column (a) in df as a dataframe (rather than as a Series).df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
type(df[['a']])
type(df.loc[:,['a']])
type(df.iloc[:,[0]])

pandas.core.frame.DataFrame

In [4]:
#3.	In df, interchange columns 'a' and 'c'.
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df[list('cbade')]

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

In [7]:
#4.	Create a generic function to interchange two columns, without hardcoding column names for the above dataset.

def switch_columns(df,col1=None,col2=None):
    colnames=df.columns.tolist()
    i1,i2=colnames.index(col1),colnames.index(col2)
    colnames[i2],colnames[i1]=colnames[i1],colnames[i2]
    return df[colnames]
df1=switch_columns(df,'a','c')
print(df1)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19